// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvibodebwkmrbjviobps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2aWJvZGVid2ttcmJqdmlvYnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5OTg5NjIsImV4cCI6MjA4OTU3NDk2Mn0.ZVbQOjHZKxUFqnybWidkIf3glYYeMDabJEhotxBREAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});